package by.academy.project.hotel.entities.user;

public enum Country {

    AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA_AND_BARBUDA, ARGENTINA, ARMENIA, AUSTRIA, AZERBAIJAN, BAHRAIN,
    BANGLADESH, BARBADOS, BELARUS, BELGIUM, BELIZE, BENIN, BHUTAN, BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BRAZIL,
    BRUNEI, BULGARIA, BURKINA_FASO, BURUNDI, CABO_VERDE, CAMBODIA, CAMEROON, CANADA, CENTRAL_AFRICAN_REPUBLIC, CHAD,
    CHANNEL_ISLANDS, CHILE, CHINA, COLOMBIA, COMOROS, CONGO, COSTA_RICA, COTE_D_IVOIRE, CROATIA, CUBA, CYPRUS, CZECH_REPUBLIC,
    DENMARK, DJIBOUTI, DOMINICA, DOMINICAN_REPUBLIC, DR_CONGO, ECUADOR, EGYPT, EL_SALVADOR, EQUATORIAL_GUINEA, ERITREA,
    ESTONIA, ESWATINI, ETHIOPIA, FAEROE_ISLANDS, FINLAND, FRANCE, FRENCH_GUIANA, GABON, GAMBIA, GEORGIA, GERMANY, GHANA,
    GIBRALTAR, GREECE, GRENADA, GUATEMALA, GUINEA, GUINEA_BISSAU, GUYANA, HAITI, HOLY_SEE, HONDURAS, HONG_KONG, HUNGARY,
    ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISLE_OF_MAN, ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKHSTAN, KENYA,
    KUWAIT, KYRGYZSTAN, LAOS, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACAO,
    MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI, MALTA, MAURITANIA, MAURITIUS, MAYOTTE, MEXICO, MOLDOVA, MONACO, MONGOLIA,
    MONTENEGRO, MOROCCO, MOZAMBIQUE, MYANMAR, NAMIBIA, NEPAL, NETHERLANDS, NICARAGUA, NIGER, NIGERIA, NORTH_KOREA,
    NORTH_MACEDONIA, NORWAY, OMAN, PAKISTAN, PANAMA, PARAGUAY, PERU, PHILIPPINES, POLAND, PORTUGAL, QATAR, RÉUNION,
    ROMANIA, RUSSIA, RWANDA, SAINT_HELENA, SAINT_KITTS_AND_NEVIS, SAINT_LUCIA, SAINT_VINCENT_AND_THE_GRENADINES,
    SAN_MARINO, SAO_TOME_AND_PRINCIPE, SAUDI_ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA_LEONE, SINGAPORE, SLOVAKIA,
    SLOVENIA, SOMALIA, SOUTH_AFRICA, SOUTH_KOREA, SOUTH_SUDAN, SPAIN, SRI_LANKA, STATE_OF_PALESTINE, SUDAN, SURINAME,
    SWEDEN, SWITZERLAND, SYRIA, TAIWAN, TAJIKISTAN, TANZANIA, THAILAND, THE_BAHAMAS, TIMOR_LESTE, TOGO, TRINIDAD_AND_TOBAGO,
    TUNISIA, TURKEY, TURKMENISTAN, UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, UNITED_KINGDOM, USA, URUGUAY,
    UZBEKISTAN, VENEZUELA, VIETNAM, WESTERN_SAHAR, YEMEN, ZAMBIA, ZIMBABWE
}