spring:
  application:
    name: hotel
  main:
    allow-circular-references: true
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  profiles:
    active:
server:
  port: 8080